### ISSUE TITLE
Run unit-tests on CI and block PRs if tests fails

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent-system-metrics#110]
It seems unit tests are not properly running on CI, recently we found a bug that would be caught by just running `go test ./...` on all supported OSes.
Ex: https://github.com/elastic/elastic-agent-system-metrics/issues/109

Our BuildKite pipeline is only defining Linux and Windows machines, it should also define MacOS.

It also seems the BuildKite tests that do run are not preventing PRs from being merged. https://github.com/elastic/elastic-agent-system-metrics/pull/103 did introduce an issue that caused the CI build to fail: https://buildkite.com/elastic/elastic-agent-system-metrics/builds/112#018bb435-2721-46d1-924b-d46b0bae356d, however this is not seen from the PR.

**Comment by jlind23** [comment]
Just added `buildkite/elastic-agent-system-metrics` as part of the required check in the branch protection rules for `main`

**Comment by belimawr** [comment]
We still need to enable running tests in MacOS, we could re-open this issue or create a new one, either way is fine for me.

I'm a BuildKite expert, but based on the pipeline definition I don't see the tests running on Windows: https://github.com/elastic/elastic-agent-system-metrics/blob/74354aae9fc189fe42f0df5e0f4d4f0dab834b1d/.buildkite/pipeline.yml#L18-L33

**Comment by cmacknz** [comment]
@belimawr open a new issue specifically for the additional platform support.

**Comment by belimawr** [comment]
> @belimawr open a new issue specifically for the additional platform support.

@cmacknz, it already got added: https://github.com/elastic/elastic-agent-system-metrics/pull/112
