### ISSUE TITLE
system process code should be less sensitive to permissions errors

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent-system-metrics#72]
Right now, `getProcStringData` will fail on any kind of error: https://github.com/elastic/elastic-agent-system-metrics/blob/bf5ec9ea5dc9b294cfbb9a647b9fd82550fd464d/metric/system/process/process_linux_common.go#L185

This is technically a regression, as on older versions of this code, it would silently skip over collecting certain values if it detected a permissions error. Code here should be able to differentiate between "permission error" and "process is gone" errors.

**Comment by fearful-symmetry** [comment]
Update: waiting on https://github.com/elastic/beats/pull/34803, will re-test once that PR is unblocked.

**Comment by ycombinator** [comment]
@fearful-symmetry @pierrehilbert Is this fixed by https://github.com/elastic/elastic-agent-system-metrics/pull/73?

**Comment by fearful-symmetry** [comment]
@ycombinator , yup. I can close this.
